#index:
#    path: /
#    controller: App\Controller\DefaultController::index
captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"
facebook_login:
    path: /connexion/check-facebook
    

# google_login:
#     path: /login/check-google
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connexion

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connexion

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/connexion.xml"
    prefix:   /connexion