# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        pubBack:
            uri_prefix:         /images/products
            upload_destination: '/public/images/products'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


      
    